name: "Lint, Test, Build & Deploy Workflow"
on: push
jobs:
  lint_test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v3
      - name: "Install Latest NodeJs"
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - name: "Perform lint"
        run: npm lint
      - name: "Perform tests"
        run: npm test

  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v3
      - name: "Install Latest NodeJs"
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - name: "Perform Build"
        run: npm run build
      - name: "Perform Deploy"
        run: |
          echo "Performing Deploy....."
          echo "......................"    