name: "Handle issues"
on: issues
jobs:
  event_details:
    runs-on: ubuntu-latest
    steps:
      - name: "Output Event Details"
        run: |
          echo "Outputting github contexts"
          echo "${{ toJson(github.event) }}"